// Curated starter exercise library used to seed new users and to top up
// existing users' libraries. Categories must match CATEGORY_OPTIONS in
// ./categories.js (lowercase). This is the single source of truth for the
// pre-loaded list — edit here to add/remove starter exercises.

export const SEED_EXERCISES = [
  // Chest
  { name: 'Barbell Bench Press', category: 'chest' },
  { name: 'Incline Barbell Bench Press', category: 'chest' },
  { name: 'Decline Barbell Bench Press', category: 'chest' },
  { name: 'Dumbbell Bench Press', category: 'chest' },
  { name: 'Incline Dumbbell Bench Press', category: 'chest' },
  { name: 'Dumbbell Fly', category: 'chest' },
  { name: 'Incline Dumbbell Fly', category: 'chest' },
  { name: 'Cable Fly', category: 'chest' },
  { name: 'Cable Crossover', category: 'chest' },
  { name: 'Pec Deck', category: 'chest' },
  { name: 'Machine Chest Press', category: 'chest' },
  { name: 'Smith Machine Bench Press', category: 'chest' },
  { name: 'Push-Up', category: 'chest' },
  { name: 'Incline Push-Up', category: 'chest' },
  { name: 'Chest Dip', category: 'chest' },
  { name: 'Landmine Press', category: 'chest' },

  // Back
  { name: 'Deadlift', category: 'back' },
  { name: 'Pull-Up', category: 'back' },
  { name: 'Chin-Up', category: 'back' },
  { name: 'Lat Pulldown', category: 'back' },
  { name: 'Wide-Grip Lat Pulldown', category: 'back' },
  { name: 'Close-Grip Lat Pulldown', category: 'back' },
  { name: 'Barbell Row', category: 'back' },
  { name: 'Pendlay Row', category: 'back' },
  { name: 'Bent-Over Dumbbell Row', category: 'back' },
  { name: 'Single-Arm Dumbbell Row', category: 'back' },
  { name: 'Seated Cable Row', category: 'back' },
  { name: 'T-Bar Row', category: 'back' },
  { name: 'Chest-Supported Row', category: 'back' },
  { name: 'Machine Row', category: 'back' },
  { name: 'Straight-Arm Pulldown', category: 'back' },
  { name: 'Rack Pull', category: 'back' },
  { name: 'Back Extension', category: 'back' },

  // Shoulders
  { name: 'Overhead Press', category: 'shoulders' },
  { name: 'Seated Dumbbell Shoulder Press', category: 'shoulders' },
  { name: 'Arnold Press', category: 'shoulders' },
  { name: 'Machine Shoulder Press', category: 'shoulders' },
  { name: 'Dumbbell Lateral Raise', category: 'shoulders' },
  { name: 'Cable Lateral Raise', category: 'shoulders' },
  { name: 'Machine Lateral Raise', category: 'shoulders' },
  { name: 'Dumbbell Front Raise', category: 'shoulders' },
  { name: 'Rear Delt Fly', category: 'shoulders' },
  { name: 'Reverse Pec Deck', category: 'shoulders' },
  { name: 'Face Pull', category: 'shoulders' },
  { name: 'Upright Row', category: 'shoulders' },
  { name: 'Barbell Shrug', category: 'shoulders' },
  { name: 'Dumbbell Shrug', category: 'shoulders' },

  // Biceps
  { name: 'Barbell Curl', category: 'biceps' },
  { name: 'EZ-Bar Curl', category: 'biceps' },
  { name: 'Dumbbell Curl', category: 'biceps' },
  { name: 'Alternating Dumbbell Curl', category: 'biceps' },
  { name: 'Hammer Curl', category: 'biceps' },
  { name: 'Incline Dumbbell Curl', category: 'biceps' },
  { name: 'Preacher Curl', category: 'biceps' },
  { name: 'Concentration Curl', category: 'biceps' },
  { name: 'Cable Curl', category: 'biceps' },
  { name: 'Spider Curl', category: 'biceps' },

  // Triceps
  { name: 'Close-Grip Bench Press', category: 'triceps' },
  { name: 'Tricep Pushdown', category: 'triceps' },
  { name: 'Rope Pushdown', category: 'triceps' },
  { name: 'Overhead Tricep Extension', category: 'triceps' },
  { name: 'Dumbbell Overhead Extension', category: 'triceps' },
  { name: 'Skull Crusher', category: 'triceps' },
  { name: 'Tricep Dip', category: 'triceps' },
  { name: 'Bench Dip', category: 'triceps' },
  { name: 'Tricep Kickback', category: 'triceps' },
  { name: 'Diamond Push-Up', category: 'triceps' },

  // Legs
  { name: 'Back Squat', category: 'legs' },
  { name: 'Front Squat', category: 'legs' },
  { name: 'Smith Machine Squat', category: 'legs' },
  { name: 'Goblet Squat', category: 'legs' },
  { name: 'Leg Press', category: 'legs' },
  { name: 'Hack Squat', category: 'legs' },
  { name: 'Bulgarian Split Squat', category: 'legs' },
  { name: 'Walking Lunge', category: 'legs' },
  { name: 'Dumbbell Lunge', category: 'legs' },
  { name: 'Step-Up', category: 'legs' },
  { name: 'Romanian Deadlift', category: 'legs' },
  { name: 'Stiff-Leg Deadlift', category: 'legs' },
  { name: 'Sumo Deadlift', category: 'legs' },
  { name: 'Good Morning', category: 'legs' },
  { name: 'Leg Extension', category: 'legs' },
  { name: 'Lying Leg Curl', category: 'legs' },
  { name: 'Seated Leg Curl', category: 'legs' },
  { name: 'Hip Thrust', category: 'legs' },
  { name: 'Glute Bridge', category: 'legs' },
  { name: 'Standing Calf Raise', category: 'legs' },
  { name: 'Seated Calf Raise', category: 'legs' },
  { name: 'Calf Press', category: 'legs' },

  // Abs
  { name: 'Plank', category: 'abs' },
  { name: 'Side Plank', category: 'abs' },
  { name: 'Crunch', category: 'abs' },
  { name: 'Bicycle Crunch', category: 'abs' },
  { name: 'Cable Crunch', category: 'abs' },
  { name: 'Sit-Up', category: 'abs' },
  { name: 'Hanging Leg Raise', category: 'abs' },
  { name: 'Lying Leg Raise', category: 'abs' },
  { name: 'Russian Twist', category: 'abs' },
  { name: 'Mountain Climber', category: 'abs' },
  { name: 'Ab Wheel Rollout', category: 'abs' },
  { name: 'V-Up', category: 'abs' },
  { name: 'Flutter Kick', category: 'abs' },
  { name: 'Dead Bug', category: 'abs' },

  // Mobility
  { name: 'Foam Rolling', category: 'mobility' },
  { name: 'Cat-Cow Stretch', category: 'mobility' },
  { name: 'Hip Flexor Stretch', category: 'mobility' },
  { name: 'Hamstring Stretch', category: 'mobility' },
  { name: 'Shoulder Dislocate', category: 'mobility' },
  { name: 'Thoracic Rotation', category: 'mobility' },
  { name: "World's Greatest Stretch", category: 'mobility' },
  { name: 'Pigeon Pose', category: 'mobility' },
  { name: 'Couch Stretch', category: 'mobility' },
  { name: '90/90 Hip Stretch', category: 'mobility' },
  { name: "Child's Pose", category: 'mobility' },
  { name: 'Downward Dog', category: 'mobility' },
];
